# Config file for automatic testing at travis-ci.org

branches:
 only:
  - master

language: python

matrix:
  include:
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.7.0

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.6.5

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.5.5

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.4.8

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=2.7.15

cache:
  directories:
    - $HOME/.pyenv/versions/3.7.0
    - $HOME/.pyenv/versions/3.6.5
    - $HOME/.pyenv/versions/3.5.5
    - $HOME/.pyenv/versions/3.4.8
    - $HOME/.pyenv/versions/2.7.15

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir $HOME/bin; ln -s $(which pip2) $HOME/bin/pip; fi
  - |
    BOOTSTRAP_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH
    BOOTSTRAP_REPO_SLUG=$TRAVIS_PULL_REQUEST_SLUG
    if [[ $BOOTSTRAP_BRANCH == "" ]]; then
      BOOTSTRAP_BRANCH=$TRAVIS_BRANCH
      BOOTSTRAP_REPO_SLUG=$TRAVIS_REPO_SLUG
    fi
    echo "BOOTSTRAP_BRANCH:$BOOTSTRAP_BRANCH"
    echo "BOOTSTRAP_REPO_SLUG:$BOOTSTRAP_REPO_SLUG"
    git clone git://github.com/$BOOTSTRAP_REPO_SLUG -b $BOOTSTRAP_BRANCH ../boostrap-scikit-ci
    pip install -U ../boostrap-scikit-ci

  - pip install -U scikit-ci-addons
  - ci_addons --install ../addons

# scikit-ci-yml.rst: start
install:
  - ci install

script:
  - ci test

after_success:
  - ci after_test
# scikit-ci-yml.rst: end
