---

branches:
 only:
  - master

version: "0.0.1.{build}"

environment:
  matrix:

    - PYTHON_DIR: "C:\\Python27-x64"
      BLOCK: "0"

    - PYTHON_DIR: "C:\\Python35-x64"
      BLOCK: "0"

init:
  - python.exe -m pip install scikit-ci-addons==0.11.0
  - python.exe -m ci_addons --install ../addons

  - ps: ../addons/appveyor/rolling-build.ps1

  - ps: |
        $env:BOOTSTRAP_BRANCH = $env:APPVEYOR_REPO_BRANCH
        $env:BOOTSTRAP_REPO_SLUG = $env:APPVEYOR_REPO_NAME
        if($env:APPVEYOR_PULL_REQUEST_NUMBER -ne $null) {
          #
          # Since AppVeyor provides only the PR number, retrieve
          # PR branch name directly from GitHub
          #
          # See also https://developer.github.com/v3/pulls/#get-a-single-pull-request
          #
          $GitHubUri="https://api.github.com/repos/scikit-build/scikit-ci/pulls/$env:APPVEYOR_PULL_REQUEST_NUMBER"
          $env:BOOTSTRAP_BRANCH=(Invoke-WebRequest            `
            -Uri $GitHubUri                                  `
            -Headers @{                                      `
              "Accept"= "application/vnd.github.v3.raw"      `
            } | ConvertFrom-Json).head.ref
          $env:BOOTSTRAP_REPO_SLUG=(Invoke-WebRequest            `
            -Uri $GitHubUri                                  `
            -Headers @{                                      `
              "Accept"= "application/vnd.github.v3.raw"      `
            } | ConvertFrom-Json).head.repo.full_name
        }
        Write-Host "BOOTSTRAP_REPO_SLUG:$env:BOOTSTRAP_REPO_SLUG"
        Write-Host "BOOTSTRAP_BRANCH:$env:BOOTSTRAP_BRANCH"

  - git clone git://github.com/%BOOTSTRAP_REPO_SLUG% -b %BOOTSTRAP_BRANCH% ../bootstrap-scikit-ci
  - python.exe -m pip install -U ../bootstrap-scikit-ci/

# scikit-ci-yml.rst: start
install:
  - python -m ci install

build_script:
  - python -m ci build

test_script:
  - python -m ci test

after_test:
  - python -m ci after_test
# scikit-ci-yml.rst: end

on_finish:
  - ps: ../addons/appveyor/enable-worker-remote-access.ps1 -check_for_block

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: dist\*

matrix:
  fast_finish: false

shallow_clone: false
